import Image from 'next/image'
import { Counter } from './components/Counter'
import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'xCreate Next App',
  description: 'Generated by create next app',
}
export default function Home() {
  return (
    <main className="flex flex-col">
      <h1>MainPage</h1>
      <Counter />
    </main>
  )
}
